import Navbar from '@/components/organisms/navbar/navbar'
import './globals.css'
import '../styles/common.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/organisms/footer/footer'
import ThemeRegistry from '@/theme/themeRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nabeel Ahmed - Frontend Developer || Innovative Web Projects Creations',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body>
        <ThemeRegistry>
          <Navbar />
          <div style={{ minHeight: "90vh" }}>
            {children}
          </div>
          <Footer />
        </ThemeRegistry>
      </body>
    </html>

  )
}
